package go.badminton;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTextField;
import javax.swing.JRadioButton;
import javax.swing.*;

public class Rental extends javax.swing.JFrame {

    public Rental() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private JFrame frame;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Pelanggan_Biasa = new javax.swing.JCheckBox();
        Pelanggan_Member = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jenis_lapangan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Lapangan = new javax.swing.JComboBox<>();
        ID_Pelanggan = new javax.swing.JTextField();
        Nama_Pelanggan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Nomor_Hp = new javax.swing.JTextField();
        harga = new javax.swing.JLabel();
        Harga = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Alamat = new javax.swing.JTextField();
        durasi_sewa1 = new javax.swing.JLabel();
        Durasi_Sewa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Clear = new javax.swing.JButton();
        Konfrimasi_Sewa = new javax.swing.JButton();
        Show_Details = new javax.swing.JButton();
        Bayar = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Data_Pemesanan = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollBar2 = new javax.swing.JScrollBar();
        BG_hitam = new javax.swing.JLabel();

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(12, 12, 12, 12, new java.awt.Color(51, 204, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 50)); // NOI18N
        jLabel8.setText("Go Badminton");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 330, 70));

        jLabel9.setText("jLabel2");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 180));

        jLabel12.setText("Sewa Lapangan Badminton");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 180, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(12, 12, 12, 12, new java.awt.Color(51, 204, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Identitas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 210, -1));

        jLabel11.setFont(new java.awt.Font("Sylfaen", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Data Pemesan");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 310, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/raket.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1520, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 220));

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(12, 12, 12, 12, new java.awt.Color(51, 204, 255)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tipe Pelanggan");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 204, 255)));
        jLabel13.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabel13ComponentAdded(evt);
            }
        });
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 130, 38));

        Pelanggan_Biasa.setForeground(new java.awt.Color(255, 255, 255));
        Pelanggan_Biasa.setText("Pelanggan Reguler");
        jPanel5.add(Pelanggan_Biasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        Pelanggan_Member.setForeground(new java.awt.Color(255, 255, 255));
        Pelanggan_Member.setText("Pelanggan Member");
        Pelanggan_Member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pelanggan_MemberActionPerformed(evt);
            }
        });
        jPanel5.add(Pelanggan_Member, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setOpaque(true);
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 220));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 380, 240));

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(12, 12, 12, 12, new java.awt.Color(51, 204, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jenis_lapangan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jenis_lapangan.setForeground(new java.awt.Color(255, 255, 255));
        jenis_lapangan.setText("Pilih Lapangan   :");
        jPanel2.add(jenis_lapangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 130, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID Pelanggan        :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Pelanggan  :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, 40));

        Lapangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shuttle Zone", "Shuttle Heaven", "Shuttle Hell", " " }));
        Lapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapanganActionPerformed(evt);
            }
        });
        Lapangan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                LapanganPropertyChange(evt);
            }
        });
        jPanel2.add(Lapangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 160, -1));

        ID_Pelanggan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(ID_Pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 180, 30));

        Nama_Pelanggan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Nama_Pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama_PelangganActionPerformed(evt);
            }
        });
        jPanel2.add(Nama_Pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 180, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("No HP                     :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 140, 20));

        Nomor_Hp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Nomor_Hp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nomor_HpActionPerformed(evt);
            }
        });
        jPanel2.add(Nomor_Hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 180, 30));

        harga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        harga.setForeground(new java.awt.Color(255, 255, 255));
        harga.setText("Total harga         :");
        jPanel2.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaActionPerformed(evt);
            }
        });
        jPanel2.add(Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 160, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Alamat                    :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatActionPerformed(evt);
            }
        });
        jPanel2.add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 180, 30));

        durasi_sewa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        durasi_sewa1.setForeground(new java.awt.Color(255, 255, 255));
        durasi_sewa1.setText("Durasi Sewa       :");
        jPanel2.add(durasi_sewa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        Durasi_Sewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Durasi_SewaActionPerformed(evt);
            }
        });
        jPanel2.add(Durasi_Sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 160, 30));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 220));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 790, 240));

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(12, 12, 12, 12, new java.awt.Color(51, 204, 255)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel4.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, -1));

        Konfrimasi_Sewa.setText("Konfrimasi Sewa");
        Konfrimasi_Sewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Konfrimasi_SewaActionPerformed(evt);
            }
        });
        jPanel4.add(Konfrimasi_Sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, -1));

        Show_Details.setText("Show Details");
        Show_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_DetailsActionPerformed(evt);
            }
        });
        jPanel4.add(Show_Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 120, -1));

        Bayar.setText("Bayar");
        Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarActionPerformed(evt);
            }
        });
        jPanel4.add(Bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, -1));

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel4.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 120, -1));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setOpaque(true);
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 220));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 230, 200, 240));

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(12, 12, 12, 12, new java.awt.Color(51, 204, 255)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Data_Pemesanan.setBackground(java.awt.SystemColor.controlShadow);
        Data_Pemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pelanggan Member", "Pelanggan Biasa", "ID*", "Nama Pelanggan", "Nomor Hp", "Alamat", "Durasi Sewa", "Lapangan", "Total Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Data_Pemesanan);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1520, 200));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1540, 220));

        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(12, 12, 12, 12, new java.awt.Color(51, 204, 255)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel7.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 80, -1));

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel7.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, -1));

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel7.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 80, -1));

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel7.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setOpaque(true);
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 220));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 230, 140, 240));
        getContentPane().add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, -30, 20, 1040));

        jScrollBar2.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        getContentPane().add(jScrollBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 790, 1560, 20));

        BG_hitam.setBackground(new java.awt.Color(0, 0, 0));
        BG_hitam.setOpaque(true);
        getContentPane().add(BG_hitam, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 2300, 1010));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel13ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13ComponentAdded

    private void LapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LapanganActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        Pelanggan_Member.setSelected(false);
        Pelanggan_Biasa.setSelected(false);
        ID_Pelanggan.setText("");
        Nama_Pelanggan.setText("");
        Nomor_Hp.setText("");
        Alamat.setText("");
        Durasi_Sewa.setText("");
        Lapangan.setSelectedItem("");
        Harga.setText("");
        
        
    }//GEN-LAST:event_ClearActionPerformed

    private void Show_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_DetailsActionPerformed
        DefaultTableModel model = (DefaultTableModel) Data_Pemesanan.getModel();
        model.addRow(new Object[]{Pelanggan_Member.isSelected(), Pelanggan_Biasa.isSelected(),
            ID_Pelanggan.getText(), Nama_Pelanggan.getText(),
            Nomor_Hp.getText(), Alamat.getText(), Harga.getText(), Lapangan.getSelectedItem(), Harga.getText(),toString(),});
               
    }//GEN-LAST:event_Show_DetailsActionPerformed

    private void LapanganPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_LapanganPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_LapanganPropertyChange

    private void Konfrimasi_SewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Konfrimasi_SewaActionPerformed
        JOptionPane.showMessageDialog(null, "Sewa Berhasil Di Komfrimasi", "", JOptionPane.OK_OPTION);
        
        DefaultTableModel model = (DefaultTableModel) Data_Pemesanan.getModel();
        model.addRow(new Object[]{Pelanggan_Member.isSelected(), Pelanggan_Biasa.isSelected(),
            ID_Pelanggan.getText(), Nama_Pelanggan.getText(),
            Nomor_Hp.getText(), Alamat.getText(), Harga.getText(), Lapangan.getSelectedItem(), Harga.getText(),toString(),});
    }//GEN-LAST:event_Konfrimasi_SewaActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        DefaultTableModel model = (DefaultTableModel) Data_Pemesanan.getModel();
        model.setRowCount(0);
        
        Pelanggan_Biasa.setSelected(false);
        Pelanggan_Member.setSelected(false);
                
        ID_Pelanggan.setText("");
        Nama_Pelanggan.setText("");
        Nomor_Hp.setText("");
        Alamat.setText("");
        Durasi_Sewa.setText("");
        Lapangan.setSelectedItem("");
        Harga.setText("");
        
    }//GEN-LAST:event_ResetActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
       frame = new JFrame ("Exit");
       if (JOptionPane.showConfirmDialog(frame, "Confirm jika anda ingin keluar", "",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION) {
       System.exit(0);
       }
    }//GEN-LAST:event_ExitActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
       DefaultTableModel model = (DefaultTableModel) Data_Pemesanan.getModel();
       if (Data_Pemesanan.getRowCount() == 0) {
        JOptionPane.showMessageDialog(null, "Tidak ada data dalam sistem sewa", "", JOptionPane.WARNING_MESSAGE);
        } else if (Data_Pemesanan.getSelectedRow() == -1) {
        JOptionPane.showMessageDialog(null, "Silakan pilih baris untuk diperbarui", "", JOptionPane.WARNING_MESSAGE);
        } else {
         JOptionPane.showMessageDialog(null, "Sistem sewa berhasil diupdate", "", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_UpdateActionPerformed

    private void Nama_PelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama_PelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nama_PelangganActionPerformed

    private void Nomor_HpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nomor_HpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nomor_HpActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) Data_Pemesanan.getModel();

        if (Data_Pemesanan.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Tidak ada data yang harus dihapus", "", JOptionPane.OK_OPTION);
        } else if (Data_Pemesanan.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Pilih baris untuk dihapus", "", JOptionPane.OK_OPTION);
        } else {
            model.removeRow(Data_Pemesanan.getSelectedRow());
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaActionPerformed

    private void AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatActionPerformed

    private void BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarActionPerformed

    }//GEN-LAST:event_BayarActionPerformed

    private void Durasi_SewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Durasi_SewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Durasi_SewaActionPerformed

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseWheelMoved

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        JOptionPane.showMessageDialog(null, "Berhasil di save", "", JOptionPane.OK_CANCEL_OPTION);
    }//GEN-LAST:event_SaveActionPerformed

    private void Pelanggan_MemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pelanggan_MemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pelanggan_MemberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JLabel BG_hitam;
    private javax.swing.JButton Bayar;
    private javax.swing.JButton Clear;
    private javax.swing.JTable Data_Pemesanan;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Durasi_Sewa;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField ID_Pelanggan;
    private javax.swing.JButton Konfrimasi_Sewa;
    private javax.swing.JComboBox<String> Lapangan;
    private javax.swing.JTextField Nama_Pelanggan;
    private javax.swing.JTextField Nomor_Hp;
    private javax.swing.JCheckBox Pelanggan_Biasa;
    private javax.swing.JCheckBox Pelanggan_Member;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Save;
    private javax.swing.JButton Show_Details;
    private javax.swing.JButton Update;
    private javax.swing.JLabel durasi_sewa1;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jenis_lapangan;
    // End of variables declaration//GEN-END:variables
}
